# graph/state.py
# ─────────────────────────────────────────────────────────────────
# Defines the shared state object that flows through LangGraph.
# Every node in the graph reads from and writes to this state.
# TypedDict gives us type hints without runtime overhead.
# ─────────────────────────────────────────────────────────────────

from typing import TypedDict, Optional


class AgentState(TypedDict):
    """
    The single shared state passed between all LangGraph nodes.

    topic        : the user's original research question
    plan         : sub-questions generated by the Planner agent
    research     : raw findings from the Researcher agent
    report       : structured report from the Writer agent
    final_output : polished final report from the Critic agent
    error        : any error message (used for conditional routing)
    """
    topic:        str
    plan:         Optional[str]
    research:     Optional[str]
    report:       Optional[str]
    final_output: Optional[str]
    error:        Optional[str]